name: Auto Post (Dry Run)

on:
  schedule:
    - cron: "0 14 * * *"   # every day at 14:00 UTC
  workflow_dispatch:        # allow manual trigger for testing

jobs:
  autopost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install feedparser tweepy python-dotenv

      - name: Run auto_post.py (dry-run)
        env:
          DRY_RUN: "true"    # keep safe for now
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python scripts/automation/auto_post.py
