name: Auto Post

on:
  schedule:
    - cron: '0 14 * * *' # every day at 14:00 UTC
  workflow_dispatch: # allow manual trigger for testing

permissions:
  contents: write # ✅ allow workflow to push commits

jobs:
  autopost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main # ✅ explicitly check out main branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Add random delay
        run: |
          DELAY=$((RANDOM % 1800))  # up to 1800 seconds (30 min)
          echo "⏳ Sleeping for $DELAY seconds before posting..."
          sleep $DELAY

            - name: Run auto_post.py
        env:
          DRY_RUN: 'false' # flip to true for testing
          USE_LLM: 'true'
          PLATFORM: 'twitter, bluesky, mastodon, devto' # or "threads" or "bluesky" or "mastodon" or combo
          POST_MODE: 'thread'
          THREAD_MODE: 'bullets'
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

          # Twitter
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

          # Threads
          THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
          THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}

          # Bluesky
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

          # Mastodon
          MASTODON_INSTANCE: ${{ secrets.MASTODON_INSTANCE }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}

          # Dev.to
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        run: python -m scripts.automation.auto_post

      - name: Commit updated posted.json
        if: github.ref == 'refs/heads/main' # ✅ safeguard: only commit on main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted.json
          git commit -m "chore: update posted.json [skip ci]" || echo "No changes to commit"
          git push origin main
